### ISSUE TITLE
any preview(image/video/youtube...)?

### ISSUE THREAD

**Issue by fukemy** [debug45/PermissionWizard#2]

**Comment by debug45** [comment]
Hi. The library does not contain any UI, except perhaps a pack of icons. I sincerely do not understand what image or video previews you propose to add. 🤷‍♂️

**Comment by fukemy** [comment]
Thanks, i saw the Example directory in project list so I thought you have any example app

**Comment by debug45** [comment]
There is indeed an example app in the repository. However, its screenshot in the documentation is unlikely to be useful, I think.

**Comment by fukemy** [comment]
sorry but i think any preview will help other people to know what your lib look like, or how beautiful of this lib, or the owner really want to support this lib....
![Screen Shot 2021-11-24 at 15 48 26](https://user-images.githubusercontent.com/8202437/143205279-bf8cdd2a-cf73-43f8-b74a-dbfe468d725a.png)

Like this:

**Comment by debug45** [comment]
SPPermissions, which you give as an example, provides a built-in beautiful UI that is shown in the screenshots. But the main task of PermissionWizard is a little different — it provides convenient API for working with system permissions, more convenient than the system.

**Comment by fukemy** [comment]
ok tks bro
