### ISSUE TITLE
Does it support screen recording permission on macOS?

### ISSUE THREAD

**Issue by jmluang** [debug45/PermissionWizard#3]
hi,Does it support screen recording permission on macOS? 
![截屏2022-01-19 下午11 37 30](https://user-images.githubusercontent.com/11557732/150163761-b6dd0267-0a4d-4597-8821-f8062c0f80cf.png)

**Comment by debug45** [comment]
Hello. Unfortunately, not yet. Permissions, that are available only on macOS, are not supported now.

**Comment by jmluang** [comment]
Sadly,  but thank you

**Comment by ixqbar** [comment]
That's bad news, it turns out it's not supported!
